In [5]:
hotels = pd.DataFrame({
    "city": ["Goa", "Goa", "Manali", "Jaipur", "Mysuru"],
    "price": [4500, 2500, 3200, 2800, 1800],
    "rating": [4.5, 3.9, 4.2, 4.0, 4.1]
})
hotels

     city  price  rating
0     Goa   4500     4.5
1     Goa   2500     3.9
2  Manali   3200     4.2
3  Jaipur   2800     4.0
4  Mysuru   1800     4.1

In [6]:
hotels.head()
hotels.info()
hotels.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    5 non-null      str
 1   price   5 non-null      int64
 2   rating  5 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 276.0 bytes

             price    rating
count     5.000000  5.000000
mean   2960.000000  4.140000
std    1001.498877  0.230217
min    1800.000000  3.900000
25%    2500.000000  4.000000
50%    2800.000000  4.100000
75%    3200.000000  4.200000
max    4500.000000  4.500000

In [7]:
hotels.head()

     city  price  rating
0     Goa   4500     4.5
1     Goa   2500     3.9
2  Manali   3200     4.2
3  Jaipur   2800     4.0
4  Mysuru   1800     4.1

In [8]:
hotels.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    5 non-null      str
 1   price   5 non-null      int64
 2   rating  5 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 276.0 bytes

In [10]:
hotels.describe()

             price    rating
count     5.000000  5.000000
mean   2960.000000  4.140000
std    1001.498877  0.230217
min    1800.000000  3.900000
25%    2500.000000  4.000000
50%    2800.000000  4.100000
75%    3200.000000  4.200000
max    4500.000000  4.500000

In [11]:
hotels[hotels["price"] < 3000]

     city  price  rating
1     Goa   2500     3.9
3  Jaipur   2800     4.0
4  Mysuru   1800     4.1

In [12]:
hotels.groupby("city")["price"].mean()

city
Goa       3500.0
Jaipur    2800.0
Manali    3200.0
Mysuru    1800.0
Name: price, dtype: float64