In [6]:
import os

print(os.getcwd())

d:\trip-planner

In [7]:
print(os.listdir())

['data', 'day1.ipynb', 'day2.ipynb']

In [9]:
print(os.listdir("data"))

['hotels.csv', 'places.csv', 'transport.csv']

In [10]:
pd.read_csv("data/hotels.csv")

,hotel_id,city,name,price_per_night,rating,category,amenities
0,1,Goa,Beachside Budget Inn,1500,3.8,budget,wifi
1,2,Goa,Calangute Comfort Stay,3500,4.2,comfort,wifi|breakfast|pool
2,3,Goa,Luxury Sands Resort,9000,4.7,luxury,wifi|breakfast|pool|spa
3,4,Mysuru,Palace Road Lodge,1200,3.9,budget,wifi
4,5,Mysuru,Hotel Pai Vista,3000,4.2,comfort,wifi|breakfast|parking
5,6,Mysuru,Aishwarya Residency,2500,3.7,budget,wifi|parking
6,7,Mysuru,ibis Styles Mysuru,5000,4.4,luxury,wifi|breakfast|pool|parking

In [12]:
hotels = pd.read_csv("data/hotels.csv")
hotels.head()

,hotel_id,city,name,price_per_night,rating,category,amenities
0,1,Goa,Beachside Budget Inn,1500,3.8,budget,wifi
1,2,Goa,Calangute Comfort Stay,3500,4.2,comfort,wifi | breakfast | pool
2,3,Goa,Luxury Sands Resort,9000,4.7,luxury,wifi | breakfast | pool | spa
3,4,Mysuru,Palace Road Lodge,1200,3.9,budget,wifi
4,5,Mysuru,Hotel Pai Vista,3000,4.2,comfort,wifi | breakfast | parking

In [13]:
hotels = pd.read_csv("data/hotels.csv")
places = pd.read_csv("data/places.csv")
transport = pd.read_csv("data/transport.csv")

print(hotels.shape, places.shape, transport.shape)
hotels.groupby("city")["price_per_night"].mean()

(7, 7) (7, 7) (5, 5)

city
Goa       4666.666667
Mysuru    2925.000000
Name: price_per_night, dtype: float64

In [14]:
print(hotels.shape, places.shape, transport.shape)

(7, 7) (7, 7) (5, 5)